### ISSUE TITLE
Create proposal for how we migrate data to ECF 2 ✈ 

### ISSUE THREAD

**Issue by claire-hughez** [DFE-Digital/ecf2#10]
### Why

We already have good reasons to think the data migration will be the riskiest part of creating ECF 2.0 and making it live for 2025.

This is because:
- it’s taken the longest for the NPQ separation
- there are lots of duplicates, missing bits and other existing data issues in ECF data
- there’s more data and tables than there is for NPQ
- probably other stuff!

We want to think of ideas for what we could do to derisk the data migration or alternative things we could pursue to help with this. This could include limiting the data we take over.

### What

Meet with team to gather ideas

Document them

### Context & links

Useful info in the LPDOB planning doc on their data migration: https://educationgovuk.sharepoint.com/:w:/s/TeacherServices/EapHtqWDfmZJiWgAU8HZ6VYB7vSkrDS9sOZN1_z5_tCqWg?e=gXD0iZ

**Comment by claire-hughez** [comment]
Here is my first draft: https://educationgovuk.sharepoint.com/sites/TeacherServices/_layouts/15/doc.aspx?sourcedoc={68e9af16-0ae8-4311-b0e7-354698178e12}&action=edit

**Comment by tonyheadford** [comment]
Looks good, I have left a comment in the doc

**Comment by gracecbrennan** [comment]
Claire has run-through with Nathan he's made a couple of suggestions. 

We will leave open for Kas to review when they are back and feeling better.
