### ISSUE TITLE
Confirm what we want to test for pulling data from DQT/TRS

### ISSUE THREAD

**Issue by mason-emily** [DFE-Digital/ecf2#102]
## Why?
When new participants are registered, we need to match them with a DQT record to check they are real, not already registered, and eligible for training. There are options worth exploring for improving the as-is approach to doing this, including pulling some more data from DQT rather than collecting from schools.

## What?
- Setting out the potential options, pros/cons/considerations 
- Scenarios we need to cater for
- Input from devs & TRA team for feasibility

## Helpful links or other information
#18 
[Slack conversation re TRA endpoints](https://ukgovernmentdfe.slack.com/archives/C02CYQTSK3K/p1724068889606149)

**Comment by mason-emily** [comment]
https://github.com/DFE-Digital/ecf2/discussions/141

**Comment by claire-hughez** [comment]
Will share a writeup of what we discussed.

**Comment by claire-hughez** [comment]
There's an update in the discussion thread to check out.

**Comment by mason-emily** [comment]
Before making final decision, we're still waiting on:

Comparing DQT names with names we have in the service

See items in thread
