### ISSUE TITLE
Understand requirements / validation for recording mentoring & mentor training

### ISSUE THREAD

**Issue by mason-emily** [DFE-Digital/ecf2#107]
## Why?
The ECF 2.0 needs a way of recording mentoring and mentor training - to inform mentor eligibility checks and calculate accurate funding. Currently, ECF 1 only records mentoring and not mentor training. 

## What?
- Collate requirements for recording mentoring and mentor training, including eligibility checks which are different for the two
- Gather list of questions left to find out from others outside of our team (e.g. ITT mentor, mentor training)
- Have a document ready with requirements and next steps

**Comment by kas-madrigal** [comment]
@aabdi18 does this align with your current research on mentors?

**Comment by kas-madrigal** [comment]
Awo will do an initial set of research since it aligns with her current user journey work and we will unpack/gather the options together

**Comment by mason-emily** [comment]
To be moved until Awo is back

**Comment by claire-hughez** [comment]
Awo is working on this now she's back.

**Comment by claire-hughez** [comment]
Awo to share link and catch up with Emily M

**Comment by aabdi18** [comment]
[Document I'm working on](https://educationgovuk-my.sharepoint.com/:w:/r/personal/awo_abdi_education_gov_uk/Documents/Mentor%20eligibity%20and%20training.docx?d=w1d6cc7941f1c4bf1bcb9082f4e1b0832&csf=1&web=1&e=dFA2Tk) currently got a few bits on mentor eligibility.
Next steps would be to look at the process of recording mentoring
