### ISSUE TITLE
Understand requirements for recording the academic year a participant starts in

### ISSUE THREAD

**Issue by mason-emily** [DFE-Digital/ecf2#108]
## Why?
In ECF 1, we have the concept of temporary and permanent 'cohorts' which inform the contract and schedule participants are assigned to. We need to understand in detail how this works so we can replicate what's needed for ECF 2 and/or make improvements where possible.

## What?
- Understand requirements for recording cohorts
- Understand detailed as is process, problems & considerations
- Agree next steps for deciding an approach for 2.0

## Helpful links or other information
Nathan's analysis here on induction start dates might be helpful: https://educationgovuk.sharepoint.com/:w:/s/TeacherServices/EYqWii8fxbtGlx70s5G0CUIB1r5qnxNgYtqwIsxi9ypHjg?e=XXy5oj

**Comment by kas-madrigal** [comment]
I covered some of this on grant funding research so happy to pick this up on next sprint

**Comment by gracecbrennan** [comment]
Ongoing

**Comment by gracecbrennan** [comment]
Aiming to complete today, with support from Kerry and Nathan

**Comment by gracecbrennan** [comment]
@kerry-b-dfe when they are back in to check status of this ticket

**Comment by mason-emily** [comment]
One consideration is that if we are asking schools to report LP/DP as part of the add ECT journey, we need to know the academic year the participant starts in first in order to present only the available LP/DP pairings for that year. The pairings change between years and we'd risk invalid pairings being selected if we present options that are not available for that ECT.

In some cases we could check the DQT overall induction start date but in many cases this date won't be recorded yet, so we'd need to ask schools
