### ISSUE TITLE
Confirm requirements for checking school eligibility

### ISSUE THREAD

**Issue by mason-emily** [DFE-Digital/ecf2#110]
## Why?
There are eligibility requirements for schools to deliver induction and training for ECTs. We need to agree the school eligibility requirements the ECF 2 service needs to check.

## What?
- Confirm school eligibility requirements ECF 2 needs to cater for (and agree any that are out of scope for us)
- Agree when / how often we need to check / re-check eligibility
- Playback to team & consider how this fits in with school sign up approach

## Helpful links or other information
[Draft schools that can access the service](https://educationgovuk.sharepoint.com/:x:/r/sites/TeacherServices/Shared%20Documents/Teacher%20Continuing%20Professional%20Development/Teacher%20CPD%20Team/ECF%202.0/Discovery/Data%20and%20business%20analysis/Schools%20that%20can%20access%20the%20service.xlsx?d=wac28f6f96b76480096f29603a08ac005&csf=1&web=1&e=6ekCR7)

**Comment by mason-emily** [comment]
Written up here: #125 
Nathan is reviewing

**Comment by claire-hughez** [comment]
A few points to confirm with policy and TRA.

**Comment by claire-hughez** [comment]
Will try to find out about Welsh inductions from TRA.

**Comment by claire-hughez** [comment]
Confirmation on Section 41.

**Comment by gracecbrennan** [comment]
Waiting Confirmation on Welsh schools - this dependent on Rob getting back.
