### ISSUE TITLE
Prepare for school user research sessions

### ISSUE THREAD

**Issue by kerry-b-dfe** [DFE-Digital/ecf2#112]
## Why?
To help us decide which changes to make to the school registration journey.

## What?
We want to test and gather initial feedback on prototypes via user research sessions.

## Helpful links or other information
[School user research frame on UR Lucid board](https://lucid.app/lucidspark/49be8a72-cd1a-43a0-aa4b-5452e8a7985a/edit?view_items=X~w3AEDiMhOT&invitationId=inv_a066f0de-5394-400e-9b69-57fc5cdd386e)

**Comment by claire-hughez** [comment]
Working on discussion guide.

**Comment by gracecbrennan** [comment]
Rose has caught up with Dom and Jas to discuss what the users will be walked through. 

Round to begin on Tuesday 17th - 2ish day round, with analysis ready the following week.

**Comment by gracecbrennan** [comment]
Recruitment emails going out this morning. 

Discussion guide will be ready for review tomorrow morning.

**Comment by claire-hughez** [comment]
Five yeses from Schools! Might need to nudge them to formally fill out the Calendly. Recruitment is going well.

Sign up sheet for UR by tomorrow. 

Lots of contacts to email if needed. 

Discussion guide to be sent over after lunch for review. Round doesn't start until Tuesday.

**Comment by claire-hughez** [comment]
Sign up sheets are waiting on times being booked by school induction tutors.

**Comment by claire-hughez** [comment]
Sessions done, analysis now. :)

**Comment by gracecbrennan** [comment]
Rose is continuing analysis today.

**Comment by gracecbrennan** [comment]
Rose is hoping to complete analysis today 

Will look to schedule session for tomorrow with design team to dsicuss recommendations

**Comment by gracecbrennan** [comment]
Session added for Thursday with whole team for playback - @RoseAsaf to check attendees list

**Comment by gracecbrennan** [comment]
Rose has a session with design team to check recommendations and larger playback to happen Thursday

**Comment by claire-hughez** [comment]
Rose is putting findings and recommendations into slide deck for tomorrow.
