### ISSUE TITLE
Conduct secondary research - analyse, synthesis and gather what we already know about providers into a central location

### ISSUE THREAD

**Issue by kerry-b-dfe** [DFE-Digital/ecf2#113]
## What?
Review previous research/knowledge about lead providers and gather useful info into a central location.

## Why?
- Reduce risk of going over old ground with providers during sessions
- Know where to go to find out info about providers

## Helpful links or other information

**Comment by gracecbrennan** [comment]
@kerry-b-dfe to share link on this.

**Comment by mason-emily** [comment]
@RoseAsaf to check for link to be added

**Comment by kerry-b-dfe** [comment]
[Secondary research board](https://lucid.app/lucidspark/49be8a72-cd1a-43a0-aa4b-5452e8a7985a/edit?view_items=22Q3M5VFGBem&invitationId=inv_a066f0de-5394-400e-9b69-57fc5cdd386e)
