### ISSUE TITLE
Prototype an 'add ECT' journey for first round of UR

### ISSUE THREAD

**Issue by JSJohal** [DFE-Digital/ecf2#124]
## Description

This ticket is to create a prototyped journey for a school user to add a new early career teacher. 

## Why? What's the need?

School users need to add information about their early career teachers to the service. We need to create a user journey in prototype form to test to capture that information. We will focus on capturing the following about the teacher:
- TRN
- Date of birth
- Email
- Name (confirm based on other details / or input)
- National insurance (this may not be present in all scenarios)
- Programme choice (provider / school led)
- Appropriate body
- Lead provider and delivery partner
- Mentor (option to add later)

## Success criteria / when is this ticket done?
- Created a clickable prototype which captures the above information and can be tested with users
- A journey which collects information needed in one transaction
- Create a variant of a confirmation message with different onwards journey based on if there's an outstanding action (such as add a mentor), considering prior insights on confirmations in @aabdi18's document
- Create a variant for capturing name vs confirming a name we've pulled back
- Create a solution to test for adding details that are typically repeated for multiple ECTs/mentor trainings (LP, DP, AB, Programme type)
- Create a solution to test for playing back and confirming details that are typically repeated for multiple ECTs/mentor trainings (LP, DP, AB, Programme type)

## What's out of scope
- Other pages such as homepage & sign in flow - prototype for this will consist of placeholder designs for those.
- Adding multiple ECTs at the same time, or adding a new mentor at the same time as an ECT
- Answering over multiple transactions, i.e. checklist, or save and return later (this may be explored in another ticket)
- Start date or start term AND predicted end date or end term

## Helpful links or other information
- [Design board](https://lucid.app/lucidspark/0fc74abe-118f-4cda-92fb-de87e4b8a36a/edit?viewport_loc=120559%2C9024%2C21547%2C10517%2C0_0&invitationId=inv_e37a643a-8ad0-4321-9455-4e30f29ef89b)

**Comment by JSJohal** [comment]
Have started creating pages in the prototype to capture information as above, continuing with this today

**Comment by JSJohal** [comment]
I've created a first draft of a clickable prototyped flow for the add ECT journey.

I've tried to cover all the points in the [ticket](https://github.com/DFE-Digital/ecf2/issues/124), namely:
- it collects all the information listed in one transaction
- show how we can have a different confirmation page depending on whether a mentor is assigned during the journey vs if the mentor is to be assigned later
- show how the flow would differ if we asked users about their 'default' programme choices at the beginning of the add an ECT journey vs if they'd already told us earlier
- added a version for collecting name vs asking user to confirm it, and a version for asking user for NINO
- added a version if we don't have any previous mentors added for the school vs if there are previous mentors

Caveats:
- content is completely placeholder, haven't connected @Dom-Collins ’s ideas to this yet - there's some obvious gaps and other bits just have my terrible phrasing
- the journey in the prototype starts from 'adding an ECT', not added in the other stuff yet like a 'dashboard', 'view your ECTs', or the sign in flow
- i'm not precious about any of the patterns particularly, and as it's a first draft there's probably some tidying up to do
- i've created a 'setup' page which isn't part of the users journey, but to specify which journey to simulate in the prototype (i.e. specify if the journey asks a user to give us their defaults at the start, or if the user has any previous mentors added)
- this is just a flow ideation in the prototype and consider the content and patterns completely open to change

Next steps are to:
- take a look, start thinking about what works well / what doesn't with these journeys - and shape into a tidier draft to share wider :smile:
- for what does work well, start thinking about content ideas so we can work those into the prototype too

I've pushed up to [this branch on GitHub ](https://github.com/DFE-Digital/ecf2-prototype/tree/sprint-8-setup)if you wanted to take a look at the code / change some stuff (you can create a new branch from it)

[Prototype can be accessed from here ](https://ecf2-prototy-sprint-8-s-znawg0.herokuapp.com/v1/school/setup)(password: ecf2), it's on a review app and isn't merged into our actual prototype yet. This links to a 'setup' page, where you can specify which flow to simulate.

For feedback / any iterations / content ideas while I'm on leave, feel free to take screenshots and put them on this [frame I've created on the design lucid board](https://lucid.app/lucidspark/0fc74abe-118f-4cda-92fb-de87e4b8a36a/edit?view_items=3OF5DtD23eaZ&invitationId=inv_e37a643a-8ad0-4321-9455-4e30f29ef89b) and add post-its or new ideas

**Comment by consult1815** [comment]
Working on this ticket concurrently https://github.com/DFE-Digital/ecf2/issues/148

**Comment by kas-madrigal** [comment]
@Dom-Collins could we say which details they have to provide for each user i.e. ECT TRN and date of birth, mentor TRA and DOB, etc... or is that too much?

**Comment by Dom-Collins** [comment]
> @Dom-Collins could we say which details they have to provide for each user i.e. ECT TRN and date of birth, mentor TRA and DOB, etc... or is that too much?

It's a fair point, I guess I've tried to keep this list at a high level as mentioning every single detail required may be info overload. I guess it gives the user a sense of what type of info is required, but maybe testing it may tell us more: 
<img width="407" alt="1" src="https://github.com/user-attachments/assets/c365459b-ef88-407f-bb30-fa0cf7cbd8e6">

**Comment by JSJohal** [comment]
Reviewed feedback yesterday and key points to work further on:

- Experiment with adding personal details first (creating more of a single journey feel rather than conjoined journeys)
- Look at reusing the ITT mentor service pattern for pulling the name back from DQT
- A few options for asking LP / DP which can be tested (i.e. search results, autocomplete, ask DP first, ask for pairing)
- Remove 'you'll need to add a mentor later' page from mid-journey

**Comment by JSJohal** [comment]
Been updating the prototype to work on the points above, and also updated the [board](https://lucid.app/lucidspark/0fc74abe-118f-4cda-92fb-de87e4b8a36a/edit?view_items=U.d9s-GBwxZ.&invitationId=inv_e37a643a-8ad0-4321-9455-4e30f29ef89b) with progress made. Working with @Dom-Collins alongside on content

**Comment by JSJohal** [comment]
Outstanding:
- Add a page for selecting LP, when DP works with more than one
- Extra confirm programme details page, so can play back LP. This would also facilitate moving the 'save programme details' to this page. Could move AB first so playback LP page follows after DP.

**Comment by JSJohal** [comment]
Content:
- think about how we explain what a delivery partner is for users who don't know what that means / consider points from policy team about the differentiation between LP / DP not being there
- do we want a list of the DPs or route off to a govuk page with that?
- do we not want to use the word 'delivery partner'?

**Comment by JSJohal** [comment]
Got some time blocked out today with @Dom-Collins today to ideate on the points above

**Comment by JSJohal** [comment]
Added content to prototype for most pages.
Outstanding:
- add confirmation pages for adding an ECT when a mentor is added / isn't added
- think about content for 'save these programme details' page
- create new Lucid frame with content updates and highlight bits yet to complete

**Comment by JSJohal** [comment]
Created a new [Lucid frame](https://lucid.app/lucidspark/0fc74abe-118f-4cda-92fb-de87e4b8a36a/edit?view_items=Xm~9tdqR-Bek&invitationId=inv_e37a643a-8ad0-4321-9455-4e30f29ef89b) with content updates and cleaned up to remove bits we don't need anymore.
Left black post-its on the bits which we still need to think through a bit more for content.
The frame above has all the original post-its with any questions and replies to them.

**Comment by gracecbrennan** [comment]
Jas is going to review this content and add to prototype

**Comment by gracecbrennan** [comment]
Dom is in the process of updating prototype today. 

We will be putting this in front of policy today.

**Comment by JSJohal** [comment]
Meeting with team and policy today, things we're picking up following it:

- Unclear how name is found from DQT, consider adding content to explain
- Consider guidance about which email to use, as support queries come in often regarding to this
- Consider making ECT name more prominent on "use default programme settings" page
- Hint / guidance around programme type may need to be more aligned with GOVUK and more prominent
- Create alternative mockup pages for capturing AB information for independent and BSO schools with dynamic functionality similar to existing schools service
- Consider moving AB question to after programme type & DP
- Have separate conversation to discuss if we would want to allow to skip AB / LP / DP (let user return to give later)
- Content updates regarding 'which delivery partner'
- Add mentored by on check answers page
- Dynamic content on confirmation page depending on whether programme type is provider led or school led

[Lucid board with post-its to the above](https://lucid.app/lucidspark/0fc74abe-118f-4cda-92fb-de87e4b8a36a/edit?view_items=Xm~9tdqR-Bek&invitationId=inv_e37a643a-8ad0-4321-9455-4e30f29ef89b)

**Comment by JSJohal** [comment]
@Dom-Collins has made several content updates as above on a branch and today I will:
- merge these changes into the prototype version we've created for research
- add functionality for session data to be stored in prototype to make as realistic as possible for research

Will review with @Dom-Collins after that and see if there's any other changes we need to make to content. If not, then will share prototype link & add latest to Lucid board

**Comment by claire-hughez** [comment]
Final confirmation page still needs to be checked out

**Comment by JSJohal** [comment]
Updated the [prototype](https://ecf2-prototy-sprint-8-s-znawg0.herokuapp.com/v2/school/setup-scenario-1) for UR

Also added a new frame to the [Lucid board](https://lucid.app/lucidspark/0fc74abe-118f-4cda-92fb-de87e4b8a36a/edit?view_items=pig.xSV74PlI&invitationId=inv_e37a643a-8ad0-4321-9455-4e30f29ef89b) with the content changes

**Comment by claire-hughez** [comment]
Ready, barring a few small content tweaks.

Confirmation page we're looking at in new ticket.
