### ISSUE TITLE
Create a prototype for signing in and requesting an account

### ISSUE THREAD

**Issue by claire-hughez** [DFE-Digital/ecf2#138]
## Description

This ticket is to create a prototyped journey for a school user to add a new early career teacher. 

## Why? What's the need?
Users need to be able to access the service.

We've decided we want schools to use DfE Sign in to do this. This is so they can manage their own onboarding using the same access management they do for other services.

## Success criteria / when is this ticket done?
- Consider if we need a page between 'Start now' and redirecting to the DfE Sign in page where they give their username and password
- We have a sign in page prototyped for using DfE Sign in
- We have a request account page prototyped for using DfE Sign in
- We have a page prototyped for if they don't have access to the service but they do have a DfE Sign in account
- Consider how to add to the frontpage that DfE Sign in is required
- Include existing work for the DfE Sign in page, as we will need it for testing

## What's out of scope
- Front/start page will be out of scope
- AB and LP sign in is out of scope
- Forgot your password

## Helpful links or other information
Teaching Vacancies already does that: https://teaching-vacancies.service.gov.uk/publishers/sign-in
DfE Sign in page of services: https://services.signin.education.gov.uk/
This service handles it by redirecting to DfE Sign in: https://apply-convert-academy.service.gov.uk/

**Comment by gracecbrennan** [comment]
Emma and Awo are picking this up together today

**Comment by aabdi18** [comment]
https://github.com/DFE-Digital/ecf2-prototype/pull/1 screenshots here for updates :)

**Comment by claire-hughez** [comment]
Will merge this when he's back and share link, can review screenshots for now.

**Comment by claire-hughez** [comment]
Awo to demo in sprint review.

Look at review comments and work on with Jas.

**Comment by claire-hughez** [comment]
Catch up on what to do with prototype today.

**Comment by mason-emily** [comment]
@JSJohal to review Github branch and check what is left that needs to be done to merge this through

**Comment by claire-hughez** [comment]
Need to decide about if we need the 'middle-page' or not.

**Comment by JSJohal** [comment]
Will review this today!

**Comment by JSJohal** [comment]
Merged into branch used for #124
