### ISSUE TITLE
Create suggestions for what personas we need for dev, staging and review environments 👩

### ISSUE THREAD

**Issue by claire-hughez** [DFE-Digital/ecf2#144]
## Why?
We need personas so we can properly test and understand how the new ECF2 services will work, with relatively realistic users and relatively realistic data.

## What?
- Create a draft of personas needed
- Consider different types of users for that persona - e.g. users from small schools, big schools, primary, secondary, different programme types
- Check this with the rest of the team
- We'll need this for schools, DFE support users, Other DfE users and appropriate body users

## Out of scope
This isn't dev work. We just need to decide what the personas are and come up with cool names for them.

**Comment by claire-hughez** [comment]
Persona ideas

Claire to put in 15 mins to confirm this with people

**Comment by kas-madrigal** [comment]
@RoseAsaf this looks like it could be right up you alley no??

**Comment by mason-emily** [comment]
@kerry-b-dfe to respond to Claire's questions and then this is done

**Comment by kerry-b-dfe** [comment]
Have answered Claire's comments. Will expand on the internal tools section as a task tomorrow.

**Comment by RoseAsaf** [comment]
https://educationgovuk-my.sharepoint.com/:w:/r/personal/rose_asaf_education_gov_uk/Documents/Manage%20Personas.docx?d=w03ac05cf58fa48bf880b43c5e7910ae2&csf=1&web=1&e=XYErWI

**Comment by claire-hughez** [comment]
that link is broken, but I think I've found it here: https://educationgovuk.sharepoint.com/:w:/r/sites/TeacherServices/_layouts/15/Doc.aspx?sourcedoc=%7B0BE0C33E-5ABE-4AA7-8B28-C59C686E6F6E%7D&file=Manage%20Personas.docx&action=default&mobileredirect=true
