### ISSUE TITLE
Summarise outcomes for ECF 2 for measuring success

### ISSUE THREAD

**Issue by mason-emily** [DFE-Digital/ecf2#146]
## Why?
We want to think about the outcomes for the ECF 2 service and how we will measure success. Emma has started providing a menu of metrics we could use, which we want to be able to link to our key outcomes

## What?
- Summarise outcomes for what success looks like from previous problems workshop
- Team session to input / review

## Helpful links or other information
[Emma's metric menu](https://lucid.app/lucidspark/b97ea0b1-f43b-4e15-8690-af471b18b591/edit?invitationId=inv_6dd9ecf1-3639-4dd2-8a19-ea9de72c234e&page=0_0#)

**Comment by claire-hughez** [comment]
Will share a link soon

**Comment by claire-hughez** [comment]
Catchup on this today.

**Comment by gracecbrennan** [comment]
@mason-emily and @consult1815 to catch-up on this today

**Comment by claire-hughez** [comment]
Emma and Emily caught up on this, Emma H will look at those outcomes in the metrics she's identified. Team session to come later.
