### ISSUE TITLE
Investigate DQT Drop-outs using web event data

### ISSUE THREAD

**Issue by consult1815** [DFE-Digital/ecf2#163]
Investigating the data provided when checking ECT DQT status on the online service. and determine which areas cause the greatest drop-out rates.

**Comment by gracecbrennan** [comment]
Some problems with code breaking - looking to debug today.

**Comment by claire-hughez** [comment]
Ready to share now :)

**Comment by gracecbrennan** [comment]
Write up is complete and @consult1815 to share

**Comment by consult1815** [comment]
Notes below on methodology:

We were curious about how frequently DQT checks were blocking progression in the ‘Add a participant’ journey on the online service. The service requires a name at the moment from the SIT completing the journey and checks this against DQT but this doesn’t have to be a requirement so the team were curious how many cases are blocked from progressing due to the current name field.

I performed the analysis in SQL, Python and Excel and investigated the web event data available, looking at those journeys which proceeded through all prior Add a Participant steps (provide a Name, TRN, DOB) and checked the initial failure/pass rates and subsequent rates once additional information was required before presenting to the team.

**Comment by consult1815** [comment]
Links to my jupyter notebooks with the code I used (only accessible to those with pre-existing access to our BQ project):

Pivoted Data Export for Analysis - 
https://console.cloud.google.com/bigquery?ws=!1m7!1m6!12m5!1m3!1secf-bq!2seurope-west2!3sbd5e3f57-4071-435d-ad48-4364ea8835cf!2e2
Sankey Chart Creation - The one I used: (Need filtered journeys from analysis excel imported): 
https://console.cloud.google.com/bigquery?ws=!1m7!1m6!12m5!1m3!1secf-bq!2seurope-west2!3s9cf7309a-3a42-4962-9d4c-437f27c960df!2e2
Sankey Chart Creation (SQL does main data wrangling, needed to use a quicker version ultimately so used above, but this is what I’d use as template going forward) - 
https://console.cloud.google.com/bigquery?ws=!1m7!1m6!12m5!1m3!1secf-bq!2seurope-west2!3s2a809b7a-c93d-4214-b45c-4ec8f9bd2a22!2e2

**Comment by consult1815** [comment]
Slack Analysis Update: https://ukgovernmentdfe.slack.com/archives/C06V31R0Z17/p1725886447947629

**Comment by consult1815** [comment]
Link to all relevant work for this analysis, including excel analysis, Sankey charts and CSVs used in python code: https://educationgovuk.sharepoint.com/:f:/r/sites/TeacherServices/Shared%20Documents/Teacher%20Continuing%20Professional%20Development/Teacher%20CPD%20Team/ECF%202.0/Test%20and%20prep/Analysis/Add%20Participant%20Journey%20-%20DQT%20Check%20Analysis%20Docs?csf=1&web=1&e=eLT0ca
