### ISSUE TITLE
Resolve service rules lingering questions ❓ 

### ISSUE THREAD

**Issue by claire-hughez** [DFE-Digital/ecf2#17]
## Why

In order to publish service rules whilst Em is away I have gathered my questions in this doc for us to review when she’s back

[Questions for Em about service rules.docx](https://educationgovuk-my.sharepoint.com/:w:/g/personal/kas_madrigal_education_gov_uk/EX6YUgtQGDRGulBwwRlScf0BzK0fQueeM03ihm0qtENeig?e=b4q9rj)

**Comment by gracecbrennan** [comment]
Emily has reviewed doc and answered questions remaining
