### ISSUE TITLE
Kick-off the work to build the data migration process

### ISSUE THREAD

**Issue by kas-madrigal** [DFE-Digital/ecf2#190]
- Present to other devs pattern we're using for the data migration process
- Use some other examples

**Comment by claire-hughez** [comment]
Build a couple of simple migrations using local stuff and talk through it? We'll spawn other tickets as needed.

**Comment by claire-hughez** [comment]
Flesh out some simple migrators to pull in the data, in the pattern Pete and Tony decided from NPQ. We can then use examples to talk about another day.

**Comment by claire-hughez** [comment]
Seed data in ECF1 is quite problematic and makes it hard to migrate. Need to catch up with Pete for anonymised copy of the prod database to use for these things.

**Comment by claire-hughez** [comment]
Connected to a copy of prod so we can start looking at real data! :O 
Abeer spoke through features they've had to do for NPQ separation. Gonna work on framework to make sure we can handle the numbers we have to do.

**Comment by claire-hughez** [comment]
Still laying the groundwork and will split later

**Comment by gracecbrennan** [comment]
@tonyheadford is going to share for feedback

**Comment by gracecbrennan** [comment]
Tony is going to run through with devs today to sanity check. 

Will look to get this PR finished as starting point

**Comment by gracecbrennan** [comment]
Tony finishing a few things off on PR - some testing and a snag and this will be complete.
