### ISSUE TITLE
Start looking at low-fidelity ideas for the first page when signed in to view ECTs and mentors

### ISSUE THREAD

**Issue by JSJohal** [DFE-Digital/ecf2#194]
## Why? What's the need?
Users need to see their early career teachers and mentors so they can see they've registered them successfully and update them if needed.

Currently, there are 3 main pages when school users sign in. Some user research suggests the first page with numbers of ECTs registered and the programme-level information isn't that helpful to users, and instead they'd prefer to see their list of ECTs immediately.

## Success criteria / when is this ticket done?
Lo-fi ideas considering some of the below:
- View a list of their ECTs / mentors
- Search or filter to see certain ECTS or mentors if necessary - start with minimum with caveat to add more as we learn
- See the state of their ECTs - statuses not created yet so don't need to get too hung up on tags etc
- See any key information about the ECT or mentor record that might be useful before clicking into individual records - think about flagging records without mentors / mentors without ECTs
- Entry point for adding ECT / mentor

## What's out of scope
- Clicking into individual ECT or mentor records and viewing them
- Complex scenarios, just early ideation

## Helpful links or other information

**Comment by gracecbrennan** [comment]
Just starting to look at design options for this - in progress

**Comment by gracecbrennan** [comment]
Dom to share designs with Jas later today

**Comment by JSJohal** [comment]
Will review this tomorrow or Monday with Dom, as ran out of time in our design meeting today while working on #124

**Comment by gracecbrennan** [comment]
Dom is going to share designs with Jas asap 

Jas has already started looking at some of the designs on board and will look to catch up today

**Comment by JSJohal** [comment]
Hasn't been looked at the last few days because of ongoing work on #124, will start to focus on this as #124 is ready for research

**Comment by claire-hughez** [comment]
Can be worked on now, prototype for testing was the priority before this.

**Comment by JSJohal** [comment]
Some design options mapped up by @Dom-Collins [here](https://lucid.app/lucidspark/92f7357d-0739-44ad-b777-bf7b1a2cf601/edit?invitationId=inv_1c581056-b5d5-4a20-a5c9-0783308f8c7b&page=0_0#), and I've added one or two also

Think a walk through with the team after standup to review and then progress to flesh out a prototyped design in the next sprint, as part of #130
