### ISSUE TITLE
UR Ways of Working

### ISSUE THREAD

**Issue by RoseAsaf** [DFE-Digital/ecf2#199]

**Comment by gracecbrennan** [comment]
We have a team call on this today to agree what this will look like.

**Comment by kerry-b-dfe** [comment]
Document started here: [UR ways of working](https://educationgovuk.sharepoint.com/:w:/r/sites/TeacherServices/Shared%20Documents/Teacher%20Continuing%20Professional%20Development/Teacher%20CPD%20Team/ECF%202.0/Test%20and%20prep/User%20Research/ECF%202%20-%20UR%20ways%20of%20working.docx?d=w7f586a91367b41969bb3072a770c20cc&csf=1&web=1&e=801umR)

**Comment by gracecbrennan** [comment]
Document underway 

UCD session on insights to actions. WOW for research, design feedback loop.

**Comment by claire-hughez** [comment]
Next week after standup, 10 mins when everyone is there to go over note-taking bits in particular.

**Comment by gracecbrennan** [comment]
Review to happen when Kerry is back tomorrow/Wed

**Comment by gracecbrennan** [comment]
Playback in tomorrow's stand-up.

**Comment by claire-hughez** [comment]
Will go over on Monday.

**Comment by claire-hughez** [comment]
Grace and Rose catching up today
