### ISSUE TITLE
Create overview documentation ❤ 

### ISSUE THREAD

**Issue by claire-hughez** [DFE-Digital/ecf2#20]
## Why

Create simple resources that give an overview of important topics within the programme.

- for each user group
- for each part of the CPD digital service that users interact with

## What

- Documentation (and playbacks if valuable)

[ECF 2.0 - Understanding our users - Lead providers.pptx](https://educationgovuk.sharepoint.com/:p:/r/sites/TeacherServices/Shared%20Documents/Teacher%20Continuing%20Professional%20Development/Teacher%20CPD%20Team/ECF%202.0/Discovery/Outputs/ECF%202.0%20-%20Understanding%20our%20users%20-%20Lead%20providers.pptx?d=w14a33185398b49d8810b5a2b8d604cec&csf=1&web=1&e=6Ecoua)

[ECF 2.0 - Understanding our users - Appropriate bodies.pptx](https://educationgovuk.sharepoint.com/:p:/r/sites/TeacherServices/Shared%20Documents/Teacher%20Continuing%20Professional%20Development/Teacher%20CPD%20Team/ECF%202.0/Discovery/Outputs/ECF%202.0%20-%20Understanding%20our%20users%20-%20Appropriate%20bodies.pptx?d=w0d2fea8d04924af398e5717d7a539706&csf=1&web=1&e=ssK6yP)

[ECF 2.0 - Understanding our users - Delivery Partners.pptx](https://educationgovuk.sharepoint.com/:p:/r/sites/TeacherServices/Shared%20Documents/Teacher%20Continuing%20Professional%20Development/Teacher%20CPD%20Team/ECF%202.0/Discovery/Outputs/ECF%202.0%20-%20Understanding%20our%20users%20-%20Delivery%20Partners.pptx?d=wb1f0190dcd33444b923ff10c4ddf2ea7&csf=1&web=1&e=kntY4f)

[ECF 2.0 - Understanding our users - Internal DfE.pptx](https://educationgovuk.sharepoint.com/:p:/r/sites/TeacherServices/Shared%20Documents/Teacher%20Continuing%20Professional%20Development/Teacher%20CPD%20Team/ECF%202.0/Discovery/Outputs/ECF%202.0%20-%20Understanding%20our%20users%20-%20Internal%20DfE.pptx?d=w88e28d079485404295e9ecfdfe0bf022&csf=1&web=1&e=DrwNhb)

[ECF 2.0 - Understanding our users - School users - SITs, ECTs & Mentors.pptx](https://educationgovuk.sharepoint.com.mcas.ms/:p:/s/TeacherServices/EbV54rHN6B1Bs-7p3YfTVccBdmzVRkjJTiyJh6EOgjvQPg?e=5Sapf8)

**Comment by claire-hughez** [comment]
Is there one for schools?

**Comment by claire-hughez** [comment]
I'd like to add all of em to our onboarding ticket

**Comment by gracecbrennan** [comment]
@kerry-b-dfe are you okay to drop the link in for schools into the list please?
