### ISSUE TITLE
Create content strategy for ECF 2 ✏ 

### ISSUE THREAD

**Issue by claire-hughez** [DFE-Digital/ecf2#21]
## What?
Create a content strategy for ECF 2.0. We need to include details such as:

1. Executive Summary

2. Goals and Objectives

3. Audience Analysis

4. Content Themes and Topics

5. Content Types and Formats

6. Content Channels

7. Measurement and Optimisation

**Comment by Dom-Collins** [comment]
Hi @claire-hughez here is the [content strategy draft](https://educationgovuk-my.sharepoint.com/:w:/g/personal/dominic_collins_education_gov_uk/EStpNKgqO51CspfAvFFs4dUBFwmTrVRGwTPEFABL3CxNQQ?e=drnGhZ).

**Comment by peteryates** [comment]
Looks good. I think the final version of this should live in [the wiki](https://github.com/DFE-Digital/ecf2/wiki).

**Comment by claire-hughez** [comment]
Hey! This looks good Dom, thank you for looking at it so quickly. I left some review comments in the document. I think it's a good start and there's some helpful things clarified in the first half, but think potentially some bits mentioned later could live elsewhere or come later.

In general, where we can, I think we should try and adopt GOVUK principles in anything we're 'publishing' like this. Similar to a design history entry.

For that end, it would be good think more about using subheadings as opposed to bullets in the text [as described here.](https://www.gov.uk/guidance/style-guide/a-to-z-of-gov-uk-style)

**Comment by gracecbrennan** [comment]
@gracecbrennan to review today
