### ISSUE TITLE
Prepare list of changes to check with ECF working group

### ISSUE THREAD

**Issue by claire-hughez** [DFE-Digital/ecf2#232]
## Why?
We want to make sure our colleagues in other teams outside CPD Digital are still kept up to date with changes we're thinking of making.

## What?
Prepare for ECF working group 2 separate sessions.

Session 1
- Go into ideas for changing the name of the service
- Go through decision to allow multiple user accounts and check if no longer collecting who is the SIT will be an issue

**Comment by gracecbrennan** [comment]
@claire-hughez has shared a deck for review ahead of working group.
