### ISSUE TITLE
Seed data 🌱 

### ISSUE THREAD

**Issue by peteryates** [DFE-Digital/ecf2#239]
Now we have a data model and are on the verge of beginning feature work we'd benefit from being able to populate the database with some useful data. When someone new to the project sets it up, it should be ready to use. Similarly, we want review apps to help people where they need to go to see a change.

We've already defined factories, so it makes sense to lean on them. We don't want the tables where the data is publicly known to be full of fake data, so be careful with the factory relationships.

We want quality over quantity, written in a modular way.

The [new seeds](https://github.com/DFE-Digital/early-careers-framework/blob/main/db/new_seeds/run.rb) approach in ECF1 works quite well, but for now we probably don't want anything that elaborate.

## Ensure the following are populated.

* [x] Schools
* [ ] Teachers
    * [ ] ECTs
    * [ ] Mentors
* [ ] [Delivery partners](https://www.gov.uk/guidance/managing-training-for-early-career-teachers#using-a-training-provider)
* [ ] [Appropriate bodies](https://www.gov.uk/government/publications/statutory-teacher-induction-appropriate-bodies/find-an-appropriate-body)
* [ ] Lead providers ([Teach First](https://www.teachfirst.org.uk/knowledge-base/early-career-framework/delivery-partners), [Ambition](https://www.ambition.org.uk/about-us/partner-directory/), [EDT](https://www.edt.org/united-kingdom/programmes/early-career-professional-development-programme/our-delivery-partners/), [BPN](https://www.bestpracticenet.co.uk/partnerships)).
* [ ] Induction periods
* [ ] Training periods
* [ ] Mentorships
* [ ] ECT at school periods
* [ ] Mentor at school periods

**Comment by claire-hughez** [comment]
Pete will check with Emma.

**Comment by gracecbrennan** [comment]
Pete is going to finish this ticket off
