### ISSUE TITLE
Investigate if our users can use DfE sign in and consider sign in approaches we could take for 2.0 🕵 

### ISSUE THREAD

**Issue by claire-hughez** [DFE-Digital/ecf2#24]
## Why

We need to find out whether our user groups for 2.0 services can use DfE sign in, and what the process for them to get access via DfE sign in may look like.

Alongside this, we should give some consideration to other potential approaches, and consider pros and cons of DfE sign in vs possible other approaches.

## What

- Investigate if our user groups can use DfE sign in
- For those user groups who possibly already use DfE sign in, what would the process to access our services look like vs those user groups who don’t / haven’t use DfE sign in previously
- Consider other potential approaches
- Document findings (maybe Lucid / possibly elsewhere)

## Helpful links

Rose’s last research round: [https://educationgovuk-my.sharepoint.com/:w:/g/personal/rose_asaf_education_gov_uk/ET2r41IiW0BGk-Ogw58J3dYBcW44RNK4k8ODZu-HXDKNiQ?e=88gmw3](https://educationgovuk-my.sharepoint.com/:w:/g/personal/rose_asaf_education_gov_uk/ET2r41IiW0BGk-Ogw58J3dYBcW44RNK4k8ODZu-HXDKNiQ?e=88gmw3 "smartCard-inline")

**Comment by gracecbrennan** [comment]
Jas has started review of journeys from DfE sign-in on new Lucid board.

**Comment by JSJohal** [comment]
Lucid board where I'm working on this: https://lucid.app/lucidspark/0fc74abe-118f-4cda-92fb-de87e4b8a36a/edit?view_items=eMEWfvqv43OX&invitationId=inv_e37a643a-8ad0-4321-9455-4e30f29ef89b

**Comment by gracecbrennan** [comment]
@JSJohal is planning to timebox this to the end of the day and this will be ready for review.

**Comment by JSJohal** [comment]
I've started a [discussion](https://github.com/DFE-Digital/ecf2/discussions/43) where I've moved findings and thoughts into from the Lucid board. The board has screenshots of existing sign-in journeys, which I've linked to in the discussion also
