### ISSUE TITLE
Discuss approach to storing or caching school admins/induction tutor

### ISSUE THREAD

**Issue by tonyheadford** [DFE-Digital/ecf2#246]
We might need know one or more school contacts or a named induction tutor for the school in order to pass this on to providers.  There are possibly issues with having multiple contacts (which one, if any, is the induction tutor?) and also our use of DfE Sign-In means that we don't need `User` records  for school admins, we could of course store or cache the user's that do come via DfE Sign In but that also needs consideration.

**Comment by peteryates** [comment]
Ah yeah - let's close this in favour of that.

See #270
