### ISSUE TITLE
Find all the unhappy paths when adding an early career teacher

### ISSUE THREAD

**Issue by claire-hughez** [DFE-Digital/ecf2#255]
## Why?
We want to make sure we've considered all the unhappy paths that can be reached whilst registering an early career teacher.

We need to do this so we can design the pages users see when DQT checks fail or something else hasn't worked successfully. 

## What?
- Consider the add an ECT and add a mentor journey and what could go wrong
- List all these unhappy paths and any ideas for how to help with them
- This should pass to design to consider how to help users in these unhappy paths afterwards (e.g. filling in a support form, re-entering details)
- An output of this could be a map (without visuals) of these different unhappy paths and endings. We could populate this later with wireframes/visuals of adding an ECT in the new service.

## Out of scope
Actually mocking up or prototyping pages in these unhappy paths.

## Helpful links or other information
@consult1815 and @claire-hughez spoke about this and can give an update.

**Comment by mason-emily** [comment]
https://lucid.app/lucidspark/b6f362cf-8201-4799-aac2-9efb0f18b2a9/edit?view_items=stv~2N7D9QMz&invitationId=inv_cf2261a1-b288-46f7-bb47-51121c5d0ec6

**Comment by claire-hughez** [comment]
Emily will try to chat to Jas about the Lucid above today

**Comment by gracecbrennan** [comment]
Emily had some time with Nathan to go through some questions. There are still some questions outstanding. 

Emily will have a chat with Jas on how design can help to accommodate some of the paths not catered for.

**Comment by gracecbrennan** [comment]
Emily has added tickets to the backlog that have come off the back of this.
