### ISSUE TITLE
Gather evidence on what language users use to refer to the services 📝 

### ISSUE THREAD

**Issue by claire-hughez** [DFE-Digital/ecf2#27]
## Why

We want to think about the naming of the services and how they’re separated. We should consider what research, analysis or data sources we already have to inform this work, given it impacts many different user groups, most of whom we cannot research with over the Summer break.

## What

Look into research, analysis, feedback, support and data sources for:

- appropriate bodies (delivery partners might help here also)
- schools

We could consider lead providers too, but it’s worth noting for MVP we aren’t committing to an interface for them.

Similarly, how we refer to them internally might be helpful, but this is hopefully something we can quickly assemble.

The output of this could be a small slide deck or word document.

## Context & links

[Feedback survey
](https://educationgovuk.sharepoint.com/:x:/r/sites/ecffeedbacksurvey/_layouts/15/Doc.aspx?sourcedoc=%7B4858E00F-7698-465D-B991-DA4893905984%7D&file=Manage%20training%20for%20early%20career%20teachers%20service%20feedback%20survey.xlsx&action=default&mobileredirect=true)

**Comment by gracecbrennan** [comment]
Dom has spoken to Emma.H to see if there's any data we can gather on language/terminology people use to refer to the Service.

Dom to catch-up with Rose and Kerry for user insights on this.

**Comment by claire-hughez** [comment]
Nathan suggested talking to Colin, Anna and Bernard on naming for this too. Could give them column of users and ask about their language.

DFE portal seems popular!

**Comment by Dom-Collins** [comment]
[Language use](https://educationgovuk-my.sharepoint.com/:w:/g/personal/dominic_collins_education_gov_uk/EQaay2tn0NNLjkJNTUpSgLQBtw7ZOcCeIeCU2rWy0510bA?e=UdGArt) (evidence so far)

**Comment by gracecbrennan** [comment]
Rose has directed Dom to UR repository to review and see if there is more evidence we can pull out from there.

**Comment by gracecbrennan** [comment]
Dom has been reviewing UR repo and has been looking through Zendesk.

**Comment by gracecbrennan** [comment]
Finding from Zendesk shared in doc attached. 

Dom has started to review naming of services

**Comment by gracecbrennan** [comment]
Dom still needs to get hold of data for search terms.

**Comment by claire-hughez** [comment]
Dom spoke to Alex F on helpdesk queries and updated language use.
Emma H just gave search terms for ECF service and will look at those too.

Going to implement to work for ABs and schools.
