### ISSUE TITLE
Plan what research can be completed over the Summer ☀ 

### ISSUE THREAD

**Issue by claire-hughez** [DFE-Digital/ecf2#28]
## Why

During the Summer, it’s tricky for us to research with ABs, DPs or schools.

The only user groups we might be able to research with is Lead providers or internal DfE colleagues.

What could we do to help inform our planned work that is first to help with this?

## What

A plan for research for the test and prep phase that considers these limitations and annual leave

## Context & links

???

**Comment by claire-hughez** [comment]
Nathan mentioned it might be good to check this with Colin, Anna and Bernard as well, as they might have an idea of what we already know or how to pitch questions.

**Comment by gracecbrennan** [comment]
Rose is going to check in with Kerry on progress here.

**Comment by gracecbrennan** [comment]
Rose is going to share today and walk-through with team.

**Comment by claire-hughez** [comment]
More specific plan for UR in August and September is the next step for this, and the actions needed for it. After that UR tickets will be made. 

There's a separate activity Rose will work on for exploratory LP work.

Rose is off from next Tuesday and Kerry is off all of next week.
