### ISSUE TITLE
Plan in-person day for 1st of August 😃

### ISSUE THREAD

**Issue by claire-hughez** [DFE-Digital/ecf2#29]
## Why

We should plan some sessions for the 1st of August. It’ll be the 2.0 team and Nathan and Emma.

## What

Plan some sessions, for example:

- a designy thing related to our current sprint goals
- a risky assumptions/unknowns session
- definition of roles
- success metrics

9:30 to 10:00 - Intros/Icebreaker (Grace)

10:05 to 10:50 -  What success looks like for ECF 2 📈 (Claire) 

10:55 to 11:10- Break

11:15 to 12:00 - Data for what success looks like 📈 (Emma H) 

12:05 to 13:05 -  Lunch 🥪 

13:10 to 14:10 - What are our risky unknowns? ❓  (Emily)

14:15 to 14:25 - Break

14:30 to 15:30 - Design Session (Jas, Awo, Dom)

15:30 - 🚋

**Comment by gracecbrennan** [comment]
Jas, Awo and Dom met to plan Design session. 

Claire meeting with Emily today to plan the unknown session

**Comment by gracecbrennan** [comment]
Emily and Claire have a session later today to plan risky unknowns
