### ISSUE TITLE
Finish the list of groundwork activities to enable us to onboard developers 🔨 

### ISSUE THREAD

**Issue by claire-hughez** [DFE-Digital/ecf2#31]
## Why

We want to onboard some developers to start building… stuff.

## What

- Create this list
- Link to it

**Comment by gracecbrennan** [comment]
@gracecbrennan to add Lorenzo and Steve to ceremonies

**Comment by peteryates** [comment]
@tonyheadford and I listed a few things today, we'll create issues with a bit more detail in them tomorrow:

* work out how we want to do frontend testing for the odd page we'll have that includes JavaScript, probably using [Playwight](https://github.com/YusukeIwaki/playwright-ruby-client)
* get some GitHub actions on the go for the quality checks we need like:
    * running tests
    * linting the code
    * accessibility checks ([example here in Playwright](https://playwright.dev/docs/accessibility-testing))
    * security checks 👮🏽‍♂️ 
* GIAS school data importing
* some examples of the code/organisation rigour we expect

**Comment by gracecbrennan** [comment]
Pete and Tony are going to convert list into issues in GitHub

**Comment by peteryates** [comment]
Done in #47, #48, #50
