### ISSUE TITLE
Create prioritisation principles for ECF2

### ISSUE THREAD

**Issue by claire-hughez** [DFE-Digital/ecf2#71]
## Why?
We know what we want to prioritise - flexibility, self-sustainability and something that works for users. These were defined in Mili's vision and strategy document for CPD.

We want to work out what we should deprioritise. Are there things or aspects we know we can focus on less?

## What?
- Produce some prioritisation principles in the format of _x over y_
- Check them with the team
- Check them with SLT

## Out of scope
It's only for ECF2.

This shouldn't take too long. It's just meant to give us as a team more of an idea of what to focus on. E.g. Flexibility over perfection!

**Comment by claire-hughez** [comment]
Flexibility over convenience
Solving evidenced problems over general improvements

**Comment by gracecbrennan** [comment]
Still in progress and slides underway

**Comment by mason-emily** [comment]
Pete and Emily have reviewed 

@gracecbrennan to take a look and this can be closed
