### ISSUE TITLE
Identify potential metrics and KPIs to support ECF 2

### ISSUE THREAD

**Issue by consult1815** [DFE-Digital/ecf2#73]
- [x] Look at research from discovery
- [ ] Access service walkthroughs
- [x] Identify and group potential metrics and KPIs
- [ ] Get team feedback about priorities and metric preferences
- [ ] Scope and map out metric building

**Comment by gracecbrennan** [comment]
Research is ongoing for this.

**Comment by gracecbrennan** [comment]
Emma is delivering an analysis for ECF schools so this ticket will be slightly on the backburner this week.

**Comment by gracecbrennan** [comment]
Head-down in discovery documents yesterday and has been drafting questions around what we can look into.

**Comment by gracecbrennan** [comment]
Emma will be thinking on metrics today ahead of meeting with Claire, Grace and Emily.M

**Comment by consult1815** [comment]
Finalising potential metrics and grouping today (22/08) for prioritisation by the team.

**Comment by consult1815** [comment]
Board is ready for team's review. Once we've identified preferred metrics I can begin scoping.

**Comment by claire-hughez** [comment]
Sent Lucidspark to Claire.

**Comment by claire-hughez** [comment]
Have a look at Emma H's discussion guide and metrics team!

**Comment by mason-emily** [comment]
@gracecbrennan to review

**Comment by consult1815** [comment]
https://lucid.app/lucidspark/b97ea0b1-f43b-4e15-8690-af471b18b591/edit?viewport_loc=2630%2C245%2C7102%2C3370%2C0_0&invitationId=inv_6dd9ecf1-3639-4dd2-8a19-ea9de72c234e
