### ISSUE TITLE
Document MVP options for AB portal replacement

### ISSUE THREAD

**Issue by bbelward** [DFE-Digital/ecf2#76]
## Why?

The database of qualified teachers and existing TRA owned AB portal must be switched off by April 2025. The business case and funding runs out so we won't have money or a mandate to delay this work any further. 

The TRA will find migrating induction data to TRS significantly less risky if a replacement AB portal is created. 

As owners of induction data, and because of doing an induction discovery in 2024, CPD are best placed to decide what an AB MVP could look like and 

## What?

**[Drafting in this doc](https://educationgovuk.sharepoint.com/:w:/r/sites/TeacherServices/Shared%20Documents/Teacher%20Continuing%20Professional%20Development/Teacher%20CPD%20Team/AB%20Portal%20Replacement%20and%20Induction%20Data%20Migration%20from%20DQT/Appropriate%20Body%20Portal%20Replacement%20MVP.docx?d=w185a1d50ab0a4115921accca28f14a94&csf=1&web=1&e=JVGdIQ)** 

- Based on what we know from Induction Discovery, kick off what the AB portal replacement must do, for example: 

* It must have a way of sharing data with TRS 
* It must fit the TRS data model 
* We must separate what is statutory data and not 
* Are there absolute musts? 

## Out of scope 

- Deciding governance - how we make sure we deliver what we need to and have the right responsibilities and comms and visibility set up with TRA

**Comment by claire-hughez** [comment]
_We must separate what is statutory data and not_
Is this definitely true? Have the TRA asked for this? TRA have not decided what data is 'statutory' and I think from talking to Rob C this is a bit of a weird word that's used strangely. The default for now is to send them everything that is currently collected in DQT. [Which is given here in the DQT API docs:](https://teacher-qualifications-api.education.gov.uk/swagger/index.html)

` },
  "induction": {
    "startDate": "2024-08-08",
    "endDate": "2024-08-08",
    "status": "Exempt",
    "statusDescription": "string",
    "certificateUrl": "string",
    "periods": [
      {
        "startDate": "2024-08-08",
        "endDate": "2024-08-08",
        "terms": 0,
        "appropriateBody": {
          "name": "string"
        }
      }`

**Comment by peteryates** [comment]
Perhaps it's more useful to categorise the AB data into two lists:

* data we need to record
* data we need to pass through to the TRS API

We need to save all of it together in our database.

**Comment by claire-hughez** [comment]
_Perhaps it's more useful to categorise the AB data into two lists:_

The TRA have stated they're not sure yet of what they want passed on, but Mili also suggested chasing them on this. I think we know at the least they want the final induction status and the induction end date. Is there anything this would be particularly useful for at this stage?

**Comment by gracecbrennan** [comment]
@emily-prudence-dfe is prioritising the questions drafted in the doc.

**Comment by gracecbrennan** [comment]
@emily-prudence-dfe has been focusing on unknowns ahead of session tomorrow.

**Comment by gracecbrennan** [comment]
@emily-prudence-dfe has been working on the MVP doc and has something to share today. 

Will be sharing with Nathan today.

**Comment by gracecbrennan** [comment]
Emily.P and Nathan had a catch up on extensions and pauses - these will be written up and shared with Phil today for approval/comment

**Comment by claire-hughez** [comment]
Set up conversations to agree things for the AB portal replacement. Trying to find time with Phil G.

**Comment by claire-hughez** [comment]
Induction period with AYTQ mainly sorted. Will get workshop in for sizing and feasibility.

Talking to TRA today.

**Comment by mason-emily** [comment]
Emily.P has been prepping for digital delivery board today. 

Yday convo with TRA transformation on timelines - end of Jan delivery date? This was agreed.

**Comment by peteryates** [comment]
This is now being tracked by #193.
