### ISSUE TITLE
Design content for School user service

### ISSUE THREAD

**Issue by Dom-Collins** [DFE-Digital/ecf2#95]
**Background**

Jas has created a number of different approaches to how the service for school users may look and work. It is a very high level flow diagram of what needs to happen within the service step by step. We need to drill down a little more and think about what the content will need to say for each step/task within the service. After some discussion, option 1 was chosen as the first approach to develop due to it's simplicity.

### Tasks

- Review flow [option 1](https://lucid.app/lucidspark/0fc74abe-118f-4cda-92fb-de87e4b8a36a/edit?viewport_loc=136353%2C11033%2C2560%2C1215%2C0_0&invitationId=inv_e37a643a-8ad0-4321-9455-4e30f29ef89b).
- Suggest ways to improve interaction and use of service components.
- Create accessible content to populate each step of the service flow.
- Generate a design that we can take forward to test with end users.

### Success criteria

- Create content for the service flow so that school users can register their ECTs.
- Each step of the flow has content that meets the needs of the user.
- We select components and interactions that are suitable.

**Comment by gracecbrennan** [comment]
Call from yesterday afternoon has created more thoughts on design ideas to be included

**Comment by gracecbrennan** [comment]
Dom is going to pick this ticket up today as priority.

**Comment by gracecbrennan** [comment]
Dom is going to have something to share on this later today.

**Comment by Dom-Collins** [comment]
Shared with Jas and Awo a [first content draft](<iframe style="border: 1px solid rgba(0, 0, 0, 0.1);" width="800" height="450" src="https://www.figma.com/embed?embed_host=share&url=https%3A%2F%2Fwww.figma.com%2Fboard%2FfzM4XFZGGYriZMt0Eq4dXO%2FOption-1%3Fnode-id%3D0-1%26t%3DCe3HjKO7npNFahvF-1" allowfullscreen></iframe>):

**Comment by claire-hughez** [comment]
Reviewed!

**Comment by Dom-Collins** [comment]
Currently adding content to prototype.

**Comment by gracecbrennan** [comment]
Has protoyped pages in Jas's pull request. 

When @JSJohal  is happy we can merge.
